# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: db/production.sqlite3
  Host: ec2-52-5-110-35.compute-1.amazonaws.com
  Database: dcv0u3hsuq8ca8
  User: oabdjrxuxrlckt
  Port: 5432
  Password: c8b03e8d9bfff14edb4396f74caa63c8224f43d4b5e0a660e01930ac47e43bd3
